In [8]:
%matplotlib inline

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pydicom
import os
import scipy.ndimage
import matplotlib.pyplot as plt

from skimage import measure, morphology
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

INPUT_FOLDER = '/Users/amy/Documents/ELVOproject/processed_data/'

In [9]:
def plot_3d(image, threshold=-300):
    
    # Position the scan upright, 
    # so the head of the patient would be at the top facing the camera
    p = image.transpose(2,1,0)
    
    verts, faces = measure.marching_cubes_classic(p, threshold)
    
    # Fancy indexing: `verts[faces]` to generate a collection of triangles
    mesh = Poly3DCollection(verts[faces])
    face_color = [0.45, 0.45, 0.75]
    mesh.set_facecolor(face_color)
    ax.add_collection3d(mesh)

    ax.set_xlim(0, p.shape[0])
    ax.set_ylim(0, p.shape[1])
    ax.set_zlim(0, p.shape[2])

    plt.show()

In [10]:
patients = os.listdir(INPUT_FOLDER)
print(patients)
patient1 = np.load(INPUT_FOLDER + patients[2])
print(patient1)

['.DS_Store', 'numpy%2F04IOS24JP70LHBGB.npy', 'numpy%2FANZM4SIQFTWG7K47.npy']
[[[-1014 -1001  -992 ... -1004  -995  -996]
  [-1008 -1007  -996 ...  -999 -1002 -1003]
  [ -993 -1008 -1005 ... -1006 -1002  -999]
  ...
  [ -155   -91   -16 ...    41    68    90]
  [   26   -22     8 ...    33    -8   -32]
  [   59   -53   -82 ...    -3   -30    -4]]

 [[-1005 -1008 -1011 ...  -987 -1011  -995]
  [ -995 -1015 -1022 ...  -993 -1008 -1003]
  [ -990 -1009 -1012 ...  -998 -1007 -1001]
  ...
  [  -88   -81   -33 ...    16    15     4]
  [   40    70    54 ...    -2     8    27]
  [    4   -79   -55 ...    44    16    14]]

 [[ -995 -1003 -1005 ...  -975 -1012  -996]
  [ -982  -995 -1015 ...  -981 -1007 -1001]
  [ -992  -994 -1004 ...  -993 -1001 -1004]
  ...
  [  -40   -39     4 ...    -8    45    28]
  [   22    14   -11 ...    24    18   -62]
  [    0   -34   -35 ...    20   -24   -22]]

 ...

 [[-1010 -1006  -999 ... -1002  -998  -996]
  [ -995 -1001  -996 ... -1004  -995  -991]
  [ -997  -9

In [11]:
def crop_center(img,cropx,cropy,cropz):
    x,y,z = img.shape
    startx = x//2-(cropx//2)
    starty = y//2-(cropy//2)    
    startz = z//2-(cropz//2)  
    return img[startx:startx+cropx,starty:starty+cropy,startz:startz+cropz]

In [12]:
image_cropped = crop_center(patient1,150,150,64)
print(image_cropped)

[[[-1006 -1012 -1004 ... -1017 -1013 -1010]
  [-1002 -1008 -1003 ... -1015 -1012 -1008]
  [-1004 -1008 -1006 ... -1012 -1008 -1010]
  ...
  [   -5    10    12 ...   -23   -36    18]
  [    7    37    38 ...     0   -31    28]
  [   16    28    40 ...    30   -28    28]]

 [[-1007 -1010 -1014 ... -1014 -1007 -1005]
  [-1005 -1011 -1012 ... -1010 -1008 -1008]
  [-1002 -1017 -1017 ... -1014 -1012 -1009]
  ...
  [   -8     7     9 ...   -34   -12    29]
  [   26    39    36 ...   -19   -29    39]
  [   36    33    43 ...   -10   -47    34]]

 [[-1005 -1007 -1005 ... -1003 -1002 -1002]
  [-1005 -1009 -1008 ... -1004 -1000 -1008]
  [-1000 -1013 -1016 ... -1003 -1004 -1007]
  ...
  [    3    13    13 ...   -42    10    48]
  [   15    19    28 ...   -31   -36    29]
  [   20    24    28 ...   -19   -67    15]]

 ...

 [[  117    53    52 ...   735  1092  1275]
  [   16    38    70 ...   286   639   962]
  [   15    48    75 ...    57   196   477]
  ...
  [   87    63    56 ...   234   505  10

In [13]:
def plot_3d(image, ax):
    
    # Position the scan upright, 
    # so the head of the patient would be at the top facing the camera
    p = image.transpose(2,1,0)
    
    #p = image
    
    verts, faces = measure.marching_cubes_classic(p, 40)

    # Fancy indexing: `verts[faces]` to generate a collection of triangles
    mesh = Poly3DCollection(verts[faces], alpha=0.70)
    face_color = [0.45, 0.45, 0.75]
    mesh.set_facecolor(face_color)
    ax.add_collection3d(mesh)

    ax.set_xlim(0, p.shape[0])
    ax.set_ylim(0, p.shape[1])
    ax.set_zlim(0, p.shape[2])

    plt.show()

In [ ]:
fig = plt.figure(figsize=(10, 10))
axis = fig.add_subplot(111, projection='3d')
plot_3d(patient1, axis)
plot_3d(image_cropped, axis)